language: node_js
node_js:
  - "8"

env:
  - TEST=main
  - TEST=docs

os: linux
dist: trusty

# Skip npm install because our script takes care of that
install: true
script: ./scripts/travis.sh $TEST_DIR

cache: "yarn"

before_deploy: cd $TRAVIS_BUILD_DIR/docs && yarn build:prod

deploy:
  provider: surge
  project: ./docs/build
  domain: material.preactjs.com
  skip_cleanup: true
  on:
    branch: release
    condition: $(./scripts/has-changes.sh docs) = "yes" && $TEST = "docs"
    node: "8"

# blocklist
branches:
  except:
    - gh-pages

addons:
  apt:
    packages:
    - jq
  firefox: "latest"

notifications:
  webhooks:
    urls:
      - https://artipost.io/travis/hook
    on_start: always
